# Uncomment the next line to define a global platform for your project
source 'https://github.com/ABTSoftware/PodSpecs.git'
platform :ios, '9.0'

target 'scicharttest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!


  pod 'SciChart'

end
